### PR TITLE
Fix the problem of compatibility issues

### LINKED ISSUE #580: Set a default value for GasPrice
**Brief of the issue**
Because of the existence of compatibility issues of GasPrice

### PR DESCRIPTION
**Pull request by ToWorld**
## Description

What is the purpose of the change?
In order to address compatibility issues of GasPrice.

Fixes #580 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Brief of your solution

Use a default GasPrice value when the GasPrice configuration is missing
or GasPrice equals 0.

## How Has This Been Tested?

Regression Test

### CODE REVIEW

File: utxo/utxo_meta.go [hunk 1]
```diff
@@ -363,6 +363,16 @@ func (uv *UtxoVM) LoadGasPrice() (*pb.GasPrice, error) {
 		if cpuRate < 0 || memRate < 0 || diskRate < 0 || xfeeRate < 0 {
 			return nil, ErrProposalParamsIsNegativeNumber
 		}
+		// To be compatible with the old version v3.3
+		// If GasPrice configuration is missing or value euqals 0, support a default value
+		if cpuRate == 0 && memRate == 0 && diskRate == 0 && xfeeRate == 0 {
```
Comment (yucaowang) [inline utxo/utxo_meta.go]: What if the user DO NOT want to use gas? Can I manually set all rate to 0 in genesis config?

Comment (yucaowang) [reply utxo/utxo_meta.go]: Agreed to solve this issue later in non-gas improvement
