### PR TITLE
Bugfix: del streams when closed by peer

### LINKED ISSUE #502: Local unconfirmTx cannot be broadcast.
**Brief of the issue**
Describe here

**Your environment**
XuperUnion and OS/Go/gcc version etc.

**Repo steps**
I generate more Tx in the slave node.
The height and utxoTotal is equal all the time.
I found some nodes have more local unconfirmed Tx in the map.

**Expected behaviours**
Describe what you expected to happen.

**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

### PR DESCRIPTION
**Pull request by ToWorld**
## Description

What is the purpose of the change?
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Cover the case that closed the stream when finding the stream has been closed by peer.

Fixes #502 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Brief of your solution

Check if stream has been closed.

## How Has This Been Tested?

Regression Test

### CODE REVIEW

File: p2pv2/stream_pool.go [hunk 1]
```diff
@@ -152,7 +153,7 @@ func (sp *StreamPool) sendMessage(ctx context.Context, msg *p2pPb.XuperMessage,
 		return err
 	}
 	if err := str.SendMessage(ctx, msg); err != nil {
-		if err.Error() == "stream reset" {
+		if err.Error() == "stream reset" || strings.HasSuffix(err.Error(), "connection reset by peer") {
```
Comment (icexin) [inline p2pv2/stream_pool.go]: Using error string to check for errors is not an idiomatic way.

Comment (fxsjy) [reply p2pv2/stream_pool.go]: Yes!
