### PR TITLE
P2p Bugfix

### LINKED ISSUE #502: Local unconfirmTx cannot be broadcast.
**Brief of the issue**
Describe here

**Your environment**
XuperUnion and OS/Go/gcc version etc.

**Repo steps**
I generate more Tx in the slave node.
The height and utxoTotal is equal all the time.
I found some nodes have more local unconfirmed Tx in the map.

**Expected behaviours**
Describe what you expected to happen.

**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

### PR DESCRIPTION
**Pull request by ToWorld**
## Description

What is the purpose of the change?

Deleting the streams when finding that the streams match with the following cases:
1.stream reset
2.connection reset by peer
3.stream closed
4.stream not valid

Fixes #502 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Brief of your solution

Check if stream has been closed.

## How Has This Been Tested?

Regression Test

### CODE REVIEW

File: p2pv2/stream_pool.go [hunk 1]
```diff
@@ -230,7 +227,9 @@ func (sp *StreamPool) sendMessageWithResponse(ctx context.Context, msg *p2pPb.Xu
 	}
 	res, err := str.SendMessageWithResponse(ctx, msg)
 	if err != nil {
-		sp.DelStream(str)
+		if common.NormalizedKVError(err) == common.ErrP2PError {
```
Comment (icexin) [inline p2pv2/stream_pool.go]: NormalizedKVError is not a good name for ErrP2PError.
ErrP2PError and the Normalized function should be in p2pv2 package?

**Comment by qizheng09** [comment]
stream limit config need to remove

File: p2pv2/stream_pool.go [hunk 2]
```diff
@@ -27,7 +27,6 @@ type StreamPool struct {
 	log log.Logger
 	// key: peer id, value: Stream
 	streams        *common.LRUCache
-	streamLength   int32
```
Comment (qizheng09) [inline p2pv2/stream_pool.go]: stream limit config need to remove
