### PR TITLE
fix #461: Contract permission check doesn't include initiator

### LINKED ISSUE #461: Contract permission check doesn't include initiator
**Brief of the issue**
Contract permission check doesn't include initiator, contract call would be failed since ACL not enough.

**Your environment**
XuperUnion master

**Repo steps**
1. Set ACL to a contact interface, give address A permission to call the interface.
2. Invoke or query the interface with address A in as initiator, keep clear of auth_require.

**Expected behaviours**
Have permission to call the interface

**What actually happened**
Returned ACL_NOT_ENOUGH error

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

### PR DESCRIPTION
**Pull request by yucaowang**
## Description

1. Combine initiator and auth require in contract permission check.
2. Add identity query interface in unified_check contract.

Fixes #461 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Brief of your solution

Please describe your solution to solve the issue or feature request.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

### CODE REVIEW

File: contractsdk/cpp/reserved/unified_check.cc [hunk 1]
```diff
@@ -238,6 +241,24 @@ DEFINE_METHOD(UnifiedCheck, identity_check) {
     ctx->ok("success");
 }
 
+// identity_query return whether address is in identity list
+// keep this method for convenience
+DEFINE_METHOD(UnifiedCheck, identity_query) {
```
Comment (ToWorld) [inline contractsdk/cpp/reserved/unified_check.cc]: Is it necessary to add an extra function of ban_query?

Comment (yucaowang) [reply contractsdk/cpp/reserved/unified_check.cc]: no need, banned_check accepts "contract" argument.
